### ISSUE TITLE
fails search for "bash" shown in gif, and every other search

### ISSUE THREAD

**Issue by mueslimak3r** [kusky3/bookmenu#1]
I have visited the "b-ok" site that this project sources books from and double checked search terms. No matter what I enter I always get the result "no books found".

The project looks cool! I may take a crack at fixing this

**Comment by mariorossi77** [comment]
there are plenty of mirrors.
it works fine for me so it shouldn't be a script issue.

**Comment by MrBreadWater** [comment]
Same problem here.

**Comment by mariorossi77** [comment]
> Same problem here.

i need more details
is your dns filtered?

**Comment by MrBreadWater** [comment]
I don't think that's the issue. I tried visiting [`URL1`](https://1lib.eu/s) in a browser and it redirected to a 404 Page (https://b-ok.cc/s?redirect=6691800). I was able to fix it by changing to: `URL1="https://b-ok.cc/s"`.

**Comment by mariorossi77** [comment]
> I don't think that's the issue. I tried visiting [`URL1`](https://1lib.eu/s) in a browser and it redirected to a 404 Page (https://b-ok.cc/s?redirect=6691800). I was able to fix it by changing to: `URL1="https://b-ok.cc/s"`.

of course, the "s" is used to do the queries.
try something like "/s/test"
opening $URL1 will always return a 404 as long as you don't provide an argument
